language: python
python:
- '3.3'
- '3.4'
- '3.5'
install:
- pip install -r requirements.txt
- pip install pytest -U pytest-runner pytest-timeout mock coverage
- pip install coveralls
script:
- python setup.py install
- coverage run --source zerolog -m py.test -v --cache-clear
after_success:
- coveralls
deploy:
  provider: pypi
  user: Emmanuel.Valette
  password:
    secure: NKX1W33MXmTMgmbUCK3ULPrq4fDXmkUTBSoHrMOcFHFzGoYYyLKxcdCTCyObLCtzVaiv2vqg5F3znxv3FqA88e+/FdEDD5RvAXbAnSGz1DStsQQ/1LL6Ia8E1RxAJVUad/JZrcJgGGe9Gx0zk49f4CUZnHQHK+WcnXAYnMA9XwmDUva+xPi8qKHHOa/Llj1uXfMsoDcIzP0oFpIs0yhsDCa3bdnYJ+wFc0CGPSy0NyLjtrZP2CfwLuDH4Ht6T37w7yUQjAt01q+2z874NIAdPXxwlaX+HeXprqwjmEvl31+FYrYielKJ1TgAUqTmacUA4kL2e45Or9ov0Dbib/9OnNYmDa8Y8ZFJMRheXJ6MqbrrYYMhbr4fGk0DJImSDkEWWw/sk3IpaP6GhyrdRXk131a6YZiWOBvjNrRJyTU9V+trQpkjudXfAF83q02iaepYE6+5BK+4MXASjIGbiFrXMq9d8Ix5KlpPmkIHCfC3zNcAJRJMZSTXV03TCpY8cd0ezAWMcdXe2WsuF4ed+uUZO+SoBh2fLFiHpYWWo/H1F4i7dFYkiZU6b4ZctV8ntZGkwPj0Nbt2ntkc0CdZqJFTwUV90rLKdQuGm9wSKi4omYyahQghCiJM1FOlFETwzLnF+eYuZn5muzGmfO8fyp8UWGcxwjPLobKxv531yRD5zPs=
  on:
    tags: true
    branch: master
    distributions: sdist bdist_wheel
    repo: TheGhouls/zerolog
