language: python
python:
  - '3.3'
  - '3.4'
  - '3.5'
install:
  - pip install -r requirements.txt
  - pip install pytest -U pytest-runner pytest-timeout mock coverage
  - pip install coveralls
script:
  - python setup.py install
  - coverage run --source zerolog -m py.test -v --cache-clear
after_success:
  - coveralls
